Squashed 'upstream/ps4jb2/' changes from a766b08..d2ebe70
d2ebe70 Cleanup 6.72 branch to remove 702 files
1ba319a Fix spanish in index702.html
301f13f Flush cache
b06920e update index702.html (#80)
bd629a4 xxx
f5d4f26 New Linux loader binaries for 7.02
3d0d1ac More configureable linux boot options (#67)
05b07fe ps4-kexec: fix vram_gb issue
556c868 Fixes: undefined reference to `__stack_chk_fail' (#66)
cb5ad02 Fix Linux payload not working on 6.72
38c2525 gdb_stub: gde app support
1b5c45f Fix ps4-kexec submodule in .gitmodules
a3f20f5 Add Linux payload binaries
0e3607f Update Cache.manifest
24cef6a linux loader: split 1gb/3gb payloads
710f6d3 Update offline cache
8bde071 7.02: add Linux support
71cbcde Add credit for 7.02 dumps
913ead6 Update Cache.manifest
def9420 Add Mira 7.02 payload
d450817 7.02: netcat via mira loader as on 6.72
042bf38 gdb_stub: buffer packet writes to prevent gdb "timeout in mid-packet" errors
13a497d gdb_stub: 7.02 support for library list
30b2f83 Fix offline cache
ec49d06 Fix HEN crash on 7.02
6d0d176 Bumb webkit-7.02
dfd8445 7.02 lending page
c2c4cc7 HEN 7.02 by ChendoChap
98e3d5b 7.02: fix kexec syscall
ac68cdf setuid(0) check before exploiting
fb1c4f4 netcat702.html: use relative paths
49659fe 7.02 netcat-only release
73a8e6d gdb_stub: fix library list in sandboxed apps
95ecec0 Add BGFT payload
f06ed10 Add sanity checks to makefiles
16297bd gdb_stub: support qXfer:libraries-svr4:read on PS4
641cc29 FWSPOOF: spoof 9.99 instead of 7.51
e8a910f Adapt gdb_stub payload for injection use.
d209d9e misc
c8bea36 Fix heisenpanic during late shutdown
1aed686 Larger heap spray to conceal memory corruption
0539b77 Add kld.
ec4a07b gdb_stub: fix base address calculation in payload mode
f627849 Revert "Unanchor broken sockets instead of keeping them in a fork"
630738e Unanchor broken sockets instead of keeping them in a fork
1c7087f Update Cache.manifest
88c33c1 Add Chinese language (#53)
58cba47 Update the instructions for new Mira UX
b0a79c9 Upgrade Mira
6aa1c25 gdbstub: support interrupt requests (Ctrl+C)
23853c3 gdb_stub: report qAttached as 0 (new process)
a1311fa gdb_stub: fix qOffsets for BLOB mode
19ef012 gdb_stub: report payload.elf as executable
9e53a54 Bump ps4-rop-8cc
5eeaac6 Update Cache.manifest
3145e28 Adding ps4-vtx-hen (#49)
f8949c4 Revert "Rename FWSPOOF to DO_NOT_USE"
b96413c Rename FWSPOOF to DO_NOT_USE
bcb9ed2 Add FWSPOOF
46eeed3 Fix FTP crash
956509e Feature/spanish language (#34)
589f10c gdb_stub: set TCP_NODELAY socket option
eee4872 Compile payloads with -Wl,-gc-sections
815412b Fix AppCache
1285af2 Update Cache.manifest
46aef66 hungarian translation update (#42)
1cea8e5 Todex Payload addition (#43)
da315db Fix game hangups
874a3ec Not close jitshm fds
3f3ec8a Fix buffer underflow in TAINTFD(ps4_printf_fd)
4be4151 Replace embedded printf with a stub to save space
069e9fd Bump ps4-rop-8cc
84885eb Repeat-until-success is back
849702e Allocate not_close array on stack
3c98514 Fix OOM-crash without alert
fff49c4 ps4-kexec: merge Baikal patches from Ps3itaTeam/ps4-kexec
5f5e2f1 Add LINUX entry to index.html
a9f423e Stability improvement
cc807bd Fix linux payload.
9885ace Add Mira-noHB to Cache.manifest
603e2ed Linux loader
52c3a87 Update 8cc
eee34f5 Add oldjb (for historical reference & to fix AppCache)
7f4e6dc Add random nonce to Cache.manifest
669a566 Fix favicon.ico on GH Pages version
3ff41f6 feat: add new changeLanguage Function (less lines), add favicon, add <head> close tag (#31)
facb4c4 Add Cache.manifest generation into Makefile
8982051 Cache Functionality (#32)
491017c Add FTP and FAKEUSB payloads
3b6f58c gdb stub: only call reloc_commands() on PS4
ece38f7 Fix dlopen
f08bb35 Fix mispaired tags
a942ca4 added hungarian language (#26)
1339545 Add GDB stub.
18e962d Added Portuguese language and made it easier to add more languages (#12)
34ebc44 Fix netcat instructions in index.html
f75ddb7 Add mira/mira2-nohb.js
f4e45ea Update index.html
2132942 No comments
517b1cb No comments
44d7b73 fx
f1516f0 Remove debug shit
4c1baf3 Add Mira-NoHB.
e6c3d85 Stable jailbreak
da0bd9a Clear CR0.TS before running saveall in kROP
d86a8d9 Clean up all related sockets except spray
5bf485d Clean up overlap_sock's RTHDR before second spray
a59889e Merge pull request #8 from theheroGAC/master
a1cd997 Update index.html
fd7fda5 Add files via upload
146ebca Add credits
300ced0 Add source code
f860d82 TCP loader (untested)
67104f1 Add a note on reliability
f1c427e Initial commit (binaries only).
REVERT: a766b08 Cleanup master branch
REVERT: 7760d00 Fix offline cache
REVERT: 482beab Initial commit

git-subtree-dir: upstream/ps4jb2
git-subtree-split: d2ebe70ef402d8e0f220b7c6ab99ba827c3a7656